In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cp_arr_1 = np.random.randint(10, size=(2, 2))

In [3]:
cp_arr_2 = cp_arr_1

In [4]:
cp_arr_1 

array([[7, 7],
       [9, 0]])

In [5]:
cp_arr_2

array([[7, 7],
       [9, 0]])

In [6]:
cp_arr_1[0,0] = 2

In [7]:
print("cp_arr_1\n", cp_arr_1)

cp_arr_1
 [[2 7]
 [9 0]]


In [8]:
print("cp_arr_2\n", cp_arr_2)

cp_arr_2
 [[2 7]
 [9 0]]


In [9]:
cp_arr_3 = cp_arr_1.view()

In [10]:
print("cp_arr_3\n", cp_arr_3)

cp_arr_3
 [[2 7]
 [9 0]]


In [11]:
cp_arr_3 = cp_arr_3.flatten('F')

In [12]:
print("cp_arr_3\n", cp_arr_3)

cp_arr_3
 [2 9 7 0]


In [13]:
print("cp_arr_1\n", cp_arr_1)

cp_arr_1
 [[2 7]
 [9 0]]


In [14]:
cp_arr_4 = cp_arr_1.copy()

In [15]:
cp_arr_4

array([[2, 7],
       [9, 0]])